### ISSUE TITLE
Removed from the workshop?

### ISSUE THREAD

**Issue by ivivaitylin** [KittenAqua/TrainworksModdingTools#146]
Just saw that this has been pulled from the Steam Workshop, was there a particular reason why?

**Comment by RawsomeGH** [comment]
@TricksterGuy said he wanted to update the mod on Steam Workshop about an hour ago. Seems like something went wrong there.

**Comment by brandonandzeus** [comment]
This has been resolved. FYI the issue was the permissions on the mod were incorrectly setup and made the item vanish for author approval when I updated the mod.

Also for visibility please file issues here from now on: https://github.com/brandonandzeus/Trainworks2 I am the new maintainer of Trainworks and development has moved over there Thanks.
